name: Release Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release-linux:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install dependencies & submodules
        run: |
          sudo apt install -y libgtkmm-3.0-dev libportaudio2 portaudio19-dev libsdl2-dev libsdl2-ttf-2.0-0 gettext
          git submodule update --init --recursive

      - name: Set build version from tag
        run: |
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build for Linux
        run: |
          cd gtk
          cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -S . -B build -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          cd build
          ninja

      - name: Compress binary and prepare for upload
        run: |
          mkdir release
          cd gtk/build
          xz -z -e snes9x-gtk
          mv snes9x-gtk.xz ../../release/snes9x-gtk3-linux-x86_64-${{ env.VERSION }}.xz

      - name: Upload Linux build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: release-linux
          path: |
            release/*.xz
          if-no-files-found: error
          retention-days: 90

      - name: Create GitHub release from generated artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ env.VERSION }}" \
            --title "${{ env.VERSION }}" \
            --target ${{ github.sha }} \
            --notes "Automated build triggered by tag push." \
            release/*.xz
